image: gitpod/workspace-bun

tasks:
  - init: bun i --frozen-lockfile
    command: bun run dev && echo KEYSTATIC=true > .env

ports:
  - port: 4321

vscode:
  extensions:
    - astro-build.astro-vscode
    - sourcegraph.cody-ai
    - bradlc.vscode-tailwindcss
    - mhutchie.git-graph
    - github.vscode-github-actions
    - astro-build.houston
    - tamasfe.even-better-toml
