name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    name: Run Lighthouse Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Build website
        uses: ./.github/workflows/build.yml

      - name: Test with Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda6cf4de7d73b29853c3f29e73a01e297bd8 # v12
        with:
          configPath: './.lighthouserc.json'
          temporaryPublicStorage: true
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Build website
        uses: ./.github/workflows/build.yml

      - name: Upload files to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=sngr-my-id
