name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Waiting test (pull request only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Run Lighthouse Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Restore Build Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: './node_modules/.astro'
          key: astro-cache-${{ hashFiles('bun.lockb', 'public/**', '**/*.astro', '**/*.md', '**/*.tsx', '**/*.ts', '**/*.mjs', '**/*.cjs') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build your site
        run: bun run build

      - name: Upload files to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=sngr-my-id
