name: Lighthouse Test

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Run Lighthouse Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: .bun-version

      - name: Restore Build Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: './node_modules/.astro'
          key: astro-cache-${{ hashFiles('bun.lockb', 'public/**', '**/*.astro', '**/*.md', '**/*.tsx', '**/*.ts', '**/*.mjs', '**/*.cjs') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build your site
        run: bun run build

      - name: Test with Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda6cf4de7d73b29853c3f29e73a01e297bd8 # v12
        with:
          configPath: './.lighthouserc.json'
          temporaryPublicStorage: true
